logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    com.navercorp.ncr: DEBUG
    java.sql: DEBUG
  path: /home1/logs/trendviewer
  file: /home1/logs/trendviewer/restservice.log

api:
  display: 5
  naver:
    news:
      client-id: vL0_aPitja6Sa27g8zjM
      client-secret: g5hvicyrBF
  youtube:
      api-key: AIzaSyBL2Zs3XK54xK7Ta3Nb6cqz54GvAlt_l2g
  duration:
    read-time: 5
    connection-time: 5
---

spring:
  profiles: prod
  data:
    rest:
      base-path: /
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://106.10.35.9:3306/trend_viewer?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&connectTimeout=30000&socketTimeout=40000&serverTimezone=UTC
    username: root
    password: ahdkqhrl
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10

server:
  port: 80
---

spring:
  profiles: dev
  data:
    rest:
      base-path: /
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:trend_viewer
    username: sa
    password:
  h2:
    console:
      enabled: true

server:
  port: 8080